version: "3"
services:
  # reverseproxy:
  #   build:
  #     context: ./udagram-reverseproxy
  #   image: sedjro/udacity-reverseproxy
  # backend_user:
  #   build:
  #     context: ./udagram-api-user
  #   image: sedjro/udacity-udagram-api-user
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: sedjro/udacity-udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: sedjro/udacity-udagram-frontend